### PR TITLE
[lint-script] lint script added to package.json

### PR DESCRIPTION
**Pull request by jtrein**
automatically excludes `node_modules`

### CODE REVIEW

**Comment by Chris-Petty** [comment]
Does this get the linter to make all the changes that it can fix? If so that is pretty useful and I'll merge. If it just shows the linter errors, atom/nuclide/what ever should already be showing that in editor.

For basic tooling changes like this that should be useful in all our projects, I think it'd be great to make a PR to react-web-app-template too.

**Comment by jtrein** [comment]
@Chris-Petty Ah, I should have included the `--fix` flag. It will try to fix some simpler errors, then output only the ones left for the user to fix by hand. Do you reckon that will be a good local dev tool?

If not, reject this one - it was out of habit.

**Comment by Chris-Petty** [comment]
No I think that will be great, in fact I had wanted exactly that for fixing the webpack config (which you ended up having a pass anyway)! Commit here and PR it for the template thanks.

**Comment by jtrein** [comment]
The only caveat I find is the granularity of the diff. At a glance it's not clear as to what exactly changed when you run `--fix`. But one should run it when they have a clean working dir, so I they know the dirty working changes are in fact lint.

**Comment by jtrein** [comment]
resolved ^^

**Pull request merged**
