### PR TITLE
[scroll-bar-madness] fixes scroll bug

### PR DESCRIPTION
**Pull request by jtrein**
🏁

### CODE REVIEW

**Comment by jtrein** [comment]
fixes #48

**Comment by jtrein** [comment]
[build ci] re-running, maybe an npm thing...

**Comment by jtrein** [comment]
merge #47 first plz 🎸

**Comment by Chris-Petty** [comment]
I'm confused... this is #47

**Comment by Chris-Petty** [comment]
[build ci]

**Comment by jtrein** [comment]
Yeah...what you said...

**Pull request merged**
